apiVersion: v1
kind: Secret
metadata:
  labels:
    app: backend
  name: firebase-secret
type: Opaque
data:
  # O valor deve ser o JSON codificado em base64
  # Exemplo de injeção em CI/CD: ${FIREBASE_CREDENTIALS_BASE64}
  FIREBASE_CREDENTIALS_JSON: ${FIREBASE_CREDENTIALS_BASE64}